### ISSUE TITLE
Should triple quoted double quotes ever get converted to triple quoted single quotes?

### ISSUE THREAD

**Issue by warsaw** [grantjenks/blue#10]
I don't like this, but I get why it's happening.  Should it?

```
--- /tmp/foo.py	2021-01-13 01:37:02.895096 +0000
+++ /tmp/foo.py	2021-01-13 01:37:15.606447 +0000
@@ -1,6 +1,6 @@
-x = """
+x = '''
 This is a TQDQS.
 
 It probably should not be converted
 into a TQSQS.
-"""
+'''
```

**Comment by grantjenks** [comment]
In this case, I do prefer the triple single quotes.  The benefits are ease of typing and consistency.

**Comment by warsaw** [comment]
It's funny; I don't know why but I always use TQDQs in these cases, but I'm okay that `blue` makes this transformation.

**Comment by zvezdan** [comment]
@grantjenks Here are my 2 cents.

 love that blue has changed all the strings back into single quotes.
I do not like that it changed triple-quoted strings into `'''string'''`.
I believe that more widespread practice is to use double quotes for triple-quoted strings, even among people who use single quotes for strings. Thus `"""string"""`

I hope we can tweak blue to do that.
Can we please reopen and reconsider this issue.

**Comment by grantjenks** [comment]
Hi @zvezdan , I'm happy to reopen and reconsider.

Maybe we can do a quick analysis to see how prevalent `"""` is vs. `'''` for non-docstrings.

But since @warsaw was similarly bugged when he first saw it, it's probably worth fixing. I don't have a strong opinion here. The `'''` behavior was just easier in the code.

**Comment by warsaw** [comment]
I created a [totally informal Twitter poll](https://twitter.com/pumpichank/status/1370216210009231366) although TBH, this is the first Twitter poll I created so I'm not sure if I did it right :smile:!

**Comment by warsaw** [comment]
```
I use double quote TQS!  77.9%
I use single quote TQS!  22.1%
68 votes·Final results
```
