### ISSUE TITLE
[Question] Active?

### ISSUE THREAD

**Issue by drewpearce** [grantjenks/blue#101]
Hi @grantjenks, @warsaw or others. I just wanted to see if this repo is still being actively maintained? I'm interested in incorporating it into my work.
It's been a year since your last release so I thought it was worth checking.

**Comment by grantjenks** [comment]
Depends kinda on what is meant by “maintained”. I’m still using it and want it to exist. But it’s not high on my list of priorities. It mostly works as-is for me.

One thing I have been wanting is the support for Jupyter notebooks that is in black. That change feels motivating to me. But it’s still not high on my priorities list.

One thing I have thought about changing is how the project kinda “works”. Right now it’s a set of monkey patches. But the black project’s use of mypyc interferes with that.

**Comment by drewpearce** [comment]
Thanks for the response. I'll keep my eyes on this project. Just heard about it today. You had me at single quotes!
