### ISSUE TITLE
Do not add a blank line after single-line docstrings

### ISSUE THREAD

**Issue by grantjenks** [grantjenks/blue#21]
Do not add a blank line after single-line docstrings (compliant with PEP257).

```
@public
class Template(string.Template):
     """Match any attribute path."""
     idpattern = r'[_a-z][_a-z0-9.]*'
```

**Comment by grantjenks** [comment]
I think the trick here is not to *add* a line. But if the user added a line it's probably fine.

**Comment by grantjenks** [comment]
I was reading through the Black source code and thought this looked pretty good:
```python
@dataclass
class Line:
    """Holds leaves and comments. Can be printed with `str(line)`."""

    depth: int = 0
    leaves: List[Leaf] = field(default_factory=list)
    # keys ordered like `leaves`
    comments: Dict[LeafID, List[Leaf]] = field(default_factory=dict)
    bracket_tracker: BracketTracker = field(default_factory=BracketTracker)
    inside_brackets: bool = False
    should_explode: bool = False

    def append(self, leaf: Leaf, preformatted: bool = False) -> None:
        """Add a new `leaf` to the end of the line.

        Unless `preformatted` is True, the `leaf` will receive a new consistent
        whitespace prefix and metadata applied by :class:`BracketTracker`.
        Trailing commas are maybe removed, unpacked for loop variables are
        demoted from being delimiters.

        Inline comments are put aside.
        """
        has_value = leaf.type in BRACKETS or bool(leaf.value.strip())
        ...
```
Notice the blank line after the class's docstring and then another blank line after the class's vars. I think that looks pretty good. I wonder if it's this logic that applies also to functions.

Also notice that the function's multi-line docstring has no blank line succeeding it.

**Comment by grantjenks** [comment]
As the demo code in #39 shows, I think Black's handling here is good. The rule seems to be that a blank line always follows a class docstring but not so for a function. I hadn't realized that when we discussed this issue before.

I think I could accept Black's formatting here.

**Comment by warsaw** [comment]
If you're right about the class/function distinction, then I'm cool with it, and my case isn't special enough to break the rules.
