### ISSUE TITLE
Docs updated for 0.6.0?

### ISSUE THREAD

**Issue by grantjenks** [grantjenks/blue#41]
When I visit https://blue.readthedocs.io/en/latest/ , I don’t see the latest docs. Is it just me (maybe caching issue?) or is something broken in the RTD integration?

**Comment by warsaw** [comment]
I think it's just you.  I definitely see the news entry for 0.6.0.

**Comment by grantjenks** [comment]
It's weird. I see this on my phone and personal laptop:
<img width="678" alt="Screen Shot 2021-02-17 at 10 23 53 PM" src="https://user-images.githubusercontent.com/118304/108314529-e529df80-716e-11eb-9288-97fa0fa1777b.png">
But the builds for latest and stable:
1. https://readthedocs.org/projects/blue/builds/13000758/
2. https://readthedocs.org/projects/blue/builds/13000754/
Both point to this commit: https://github.com/grantjenks/blue/commit/fb449281e58376ccaadad51111ff3443442d7adb which is correct.

I don't get it. I tried reloading too with cache disabled to no avail.

**Comment by warsaw** [comment]
Weird!  Here's what I see in Brave:

<img width="714" alt="Screen Shot 2021-02-18 at 10 44 22" src="https://user-images.githubusercontent.com/210184/108405856-797b5d00-71d6-11eb-8bd0-e9e19dd90159.png">

But I just looked at the page in a Safari that I'd never used for this purpose before, and I see the same thing you do.  What, what, what?!

**Comment by grantjenks** [comment]
Seems fixed to me. I see 0.7.0 at https://blue.readthedocs.io/en/latest/
