### ISSUE TITLE
blue -t py39 is not supported

### ISSUE THREAD

**Issue by warsaw** [grantjenks/blue#44]
```
% blue -t py39
Usage: blue [OPTIONS] [SRC]...
Try 'blue -h' for help.

Error: Invalid value for '-t' / '--target-version': invalid choice: py39. (choose from py27, py33, py34, py35, py36, py37, py38)
```

What it should do is:

```
% blue -t py39
No Path provided. Nothing to do 😴
```

This is because we're depending on `black 20.8b1` which also doesn't support `py39`.  However `black` git HEAD does support it so maybe we just wait for the next (non-beta) release.  Alternatively, maybe we can just monkeypatch support aligning `py39` to `py38`.

**Comment by grantjenks** [comment]
Will be fixed by #54
