### ISSUE TITLE
Is this repository still active? The last update was 9 month ago

### ISSUE THREAD

**Issue by sshishov** [grantjenks/blue#94]
We are using this library for long time. And we prefer `blue` over `black` as we believe in single quotes!

Unfortunately this repository was not updated for a long time and because of this our testing dependencies are outdated (because of flake8 dependency)

The question is, do we still maintain this project? Do we still fix issues and add enhancements + features? Are we still up-to-date with black (as in the beginning it was just a fork with small modifications)?

**Comment by effigies** [comment]
For what it's worth, the easiest way to use blue is to use `pipx install blue`, which will put it into its own virtual environment and link to the executable in `~/.local/bin`. This isolation keeps it from conflicting with other tools.

**Comment by grantjenks** [comment]
I’m a maintainer and I still use blue.

pipx is a good solution, as is tox which I use in my projects. Both will keep blue isolated from other tools.

**Comment by sshishov** [comment]
Hi @grantjenks , feel free to close this issue if you feel it right.

Just want to add my note here as we have moved to "black", in the beginning everyone hated these double quotes but really based on the font type you can make it look almost similar to "blue" representation. Now we are okay with "black", not a big deal.

Why have we made this choice and moved to "black" from "blue"? Everything is easy, we are not using separate environments to install linting packages and to install testing packages and to install any other packages. We have one virtualenvironment which is activated automatically when you enter the docker container (as user) and you literally do not need to do anything. The same environment is used for local development and for VSCode extensions. To have different envs for different tasks would be a nightmare for configuration TBH. We have 2 main environments (production) and (development), where production has only the production required packages and development has everything (ipdb, ipython, pytest, flake8, black and so on...) Therefore to keep our DEV environment up-to-date we have  to update it (we use dependabot)... unfortunately because soma packages are stuck in ancient versions to support flake8 (v4) instead of (v6) a lot of out dependencies were not just updated. That is the main reason, actually...

This was just my five cents, sorry for the long read.

**Comment by grantjenks** [comment]
There’s no update since my last post. I’m still a maintainer and I still use blue for projects at work and home.

“Active” is a relative term. And it would seem, based on your posts, that it is not active enough for you.
